export const HALAL_STATUSES = ["Fully Halal", "Partially Halal"];

export const CUISINE_GROUPS = {
  "Fast Food": ["Fast Food", "Street Food", "Fried Chicken", "Pizza", "Burgers"],
  "Asian": ["Chinese", "Taiwanese", "Thai", "Malaysian", "Japanese", "Vietnamese", "Korean", "Pan-Asian"],
  "Desi": ["Indian", "Pakistani"],
  "Middle Eastern": ["Lebanese", "Yemeni", "Somali", "Middle Eastern"],
  "African": ["African", "Afro-Portuguese"],
  "European": ["Italian", "French", "Spanish", "Greek", "British"],
  "Steak": ["Steak", "Steak House"],
  "American": ["American", "Mexican", "Caribbean"],
  "Mediterranean": ["Turkish", "Mediterranean"],
  "Dessert": ["Dessert", "Bakery"],
  "Cafe": ["Cafe", "Coffee Shop"],
};

export function getCuisineEmoji(cuisine) {
  const cuisineEmojis = {
    "Desi": "🍛",
    "Asian": "🍜",
    "European": "🍝",
    "Italian": "🍝",
    "Chinese": "🍜",
    "Taiwanese": "🍜",
    "Indian": "🍛",
    "Pakistani": "🍛",
    "Sri Lankan": "🍛",
    "Thai": "🍲",
    "Malaysian": "🍲",
    "Japanese": "🍣",
    "Mexican": "🌮",
    "American": "🍔",
    "British": "🍖",
    "French": "🥐",
    "Spanish": "🥘",
    "Greek": "🥗",
    "Turkish": "🍢",
    "Lebanese": "🥙",
    "Vietnamese": "🍲",
    "Korean": "🍱",
    "African": "🍲",
    "Caribbean": "🍛",
    "Middle Eastern": "🍢",
    "Yemeni": "🍢",
    "Somali": "🍛",
    "Mediterranean": "🥗",
    "Dessert": "🍰",
    "Bakery": "🍞",
    "Cafe": "☕",
    "Fast Food": "🍔",
    "Street Food": "🍢",
    "Fried Chicken": "🍗",
    "Pizza": "🍕",
    "Burgers": "🍔",
    "Hamburger": "🍔",
    "Steak": "🥩",
    "Steak House": "🥩",
    "Pan-Asian": "🍲",
  };

  return cuisineEmojis[cuisine] || "🍽️";
}
