export function getCuisineEmoji(cuisine) {
  const cuisineEmojis = {
    "Desi": "🍛",
    "Asian": "🍜",
    "European": "🍝",
    "Italian": "🍝",
    "Chinese": "🍜",
    "Taiwanese": "🍜",
    "Indian": "🍛",
    "Pakistani": "🍛",
    "Thai": "🍲",
    "Malaysian": "🍲",
    "Japanese": "🍣",
    "Mexican": "🌮",
    "American": "🍔",
    "British": "🍖",
    "French": "🥐",
    "Spanish": "🥘",
    "Greek": "🥗",
    "Turkish": "🍢",
    "Lebanese": "🥙",
    "Vietnamese": "🍲",
    "Korean": "🍱",
    "African": "🍲",
    "Caribbean": "🍛",
    "Middle Eastern": "🍢",
    "Yemeni": "🍢",
    "Somali": "🍛",
    "Mediterranean": "🥗",
    "Dessert": "🍰",
    "Bakery": "🍞",
    "Cafe": "☕",
    "Fast Food": "🍔",
    "Street Food": "🍢",
    "Fried Chicken": "🍗",
    "Pizza": "🍕",
    "Burgers": "🍔",
    "Steak": "🥩",
    "Pan-Asian": "🍲",
  };

  return cuisineEmojis[cuisine] || "🍽️";
}
